// Curated IANA timezone list for the reminder-time override. Mirrors the
// server's country→timezone set plus common zones. `null` means "automatic"
// (the server derives it from the tailor's country).
export const TIMEZONES: string[] = [
  'Africa/Douala',
  'Africa/Lagos',
  'Africa/Accra',
  'Africa/Abidjan',
  'Africa/Dakar',
  'Africa/Nairobi',
  'Africa/Dar_es_Salaam',
  'Africa/Kampala',
  'Africa/Addis_Ababa',
  'Africa/Johannesburg',
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Algiers',
  'Africa/Tunis',
  'Africa/Kigali',
  'Africa/Kinshasa',
  'Africa/Libreville',
  'Africa/Lome',
  'Africa/Porto-Novo',
  'Africa/Ouagadougou',
  'Africa/Bamako',
  'Africa/Lusaka',
  'Africa/Harare',
  'Africa/Luanda',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'America/New_York',
  'America/Toronto',
  'America/Sao_Paulo',
  'Asia/Kolkata',
  'Asia/Karachi',
  'Asia/Dubai',
  'Asia/Riyadh',
  'Asia/Manila',
  'UTC',
];
